### ISSUE TITLE
RuntimeError: CUDA out of memory.

### ISSUE THREAD

**Issue by wyk201722** [THUDM/SCR#1]
I tried to  reproduce on 2 Tesla  V100s. Only one GPU core in use.
In ubuntu  18.04. with ogb = 1.3.3, numpy = 1.20.3, cogdl = 0.5.2

After the 1st training staged ended, the error message came out below:
"""
Best Epoch 350, Val 0.9310, Test 0.8349
This history model Train ACC is 0.9655824835338097
This history model Valid ACC is 0.9309564377082115
This history model Test ACC is 0.8348915611694232
Stage: 1, confident nodes: 1766768
Stage: 1, confident_cons nodes: 981983
use teacher label
GAMLP
R_GAMLP_RLU
# Params: 3335831
Traceback (most recent call last):
  File "CRGNN-main/main.py", line 413, in <module>
    main(args)
  File "CRGNN-main/main.py", line 297, in main
    best_val, best_test = run(args, device)
  File "CRGNN-main/main.py", line 223, in run
    loss, acc = train_rlu_consis(model, train_loader, enhance_loader, optimizer, evaluator, device, feats, labels,
  File "CRGNN-main/utils.py", line 102, in train_rlu_consis
    output_att_f = model(batch_feats, label_emb[idx_3].to(device))
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "CRGNN-main/model.py", line 340, in forward
    input_list.append(self.process[i](feature_list[i]))
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/CRGNN-main/layer.py", line 93, in forward
    x = self.dropout(self.prelu(self.bns[layer_id](x)))
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/modules/batchnorm.py", line 168, in forward
    return F.batch_norm(
  File "/home/anaconda3/lib/python3.9/site-packages/torch/nn/functional.py", line 2282, in batch_norm
    return torch.batch_norm(
RuntimeError: CUDA out of memory. Tried to allocate 50.00 MiB (GPU 0; 31.75 GiB total capacity; 6.97 GiB already allocated; 42.12 MiB free; 7.01 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
"""
It seems like there is still available sapce in GPU, but this error just came out.
Searching online lots of people met this error. Some solved it by modifying the batch size, some tried in the same way but failed. Have you met this problem before in the training stage? Thank you very much.

**Comment by yf-he** [comment]
Hi，
This error is weird because I was using an RTX3090 with 24GB GPU memory in my experiments. What is the batch_size you are currently experimenting with? In general, reducing batch_size can directly reduce the amount of GPU memory used, so maybe you can try it.  Or you could check to see if another program is taking up some of the GPU memory.
If it is determined that it is not caused by insufficient GPU memory, we can then think about whether there is another problem.

**Comment by wyk201722** [comment]
Thanks for you reply. I just ran the command once again, and the error disappeared. 

The error happened when I tried to reproduce the "GAMLP+RLU+SCR for ogbn-products" result with the following command "python main.py --use-rlu --method R_GAMLP_RLU --stages 400 300 300 300 300 300 --train-num-epochs 0 0 0 0 0 0 --threshold 0.85 --input-drop 0.2 --att-drop 0.5 --label-drop 0 --pre-process --residual --dataset ogbn-products --num-runs 10 --eval 10 --act leaky_relu --batch_size 50000 --patience 300 --n-layers-1 4 --n-layers-2 4 --bns --gama 0.1 --consis --tem 0.5 --lam 0.1 --hidden 512 --ema"

The error happened after 1st stage training end, before the second stage 
My hardware device is Tesla V100 with 32GB. There was no other programs occupying the GPU memory during the traning. What's why I was thinking GPU memory should not be the problem.  But I'm not sure whether it will happen in the next time.

Thank you very much
